apiVersion: v1
kind: Namespace
metadata:
  name: bayora-control
  labels:
    bayora.zone: control-plane
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: bayora-red
  labels:
    bayora.zone: red-zone
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: bayora-blue
  labels:
    bayora.zone: blue-zone
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: bayora-llm
  labels:
    bayora.zone: llm-zone
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: bayora-audit
  labels:
    bayora.zone: audit-zone
    pod-security.kubernetes.io/enforce: restricted
